Repository DevKor-github/ku-key_front, pull requests merged in 2024-09, with the labels that each got.

#31 Fix/#25
  src/components/community/post/CommentInput.tsx
  src/components/community/post/PostComment.tsx
  src/util/useTextArea.ts
Labels: bug

#34 [#28] Fix/club layout
  src/components/club/SearchArea.tsx
  src/pages/ClubPage.tsx
  src/pages/SchedulePage.tsx
Labels: bug

#61 언어 Feature 배포~🚀
  panda.config.ts
  src/api/hooks/user.ts
  src/api/types/user.ts
  src/components/mypage/Contents/PointShop/Showcase.tsx
  src/components/mypage/Contents/PublicProfile.tsx
  src/components/mypage/UserInfo.tsx
  src/components/ui/chip/index.tsx
  src/components/ui/dropdown/LanguageDropdown.tsx
  src/lib/constants/language.ts
  src/lib/recipes/chip.ts
  src/lib/recipes/index.ts
  src/util/getKeyByValue.ts
Labels: Deploy

#60 Fix/timetable ux
  src/api/hooks/timetable.ts
  src/components/home/Announcement/InsituteProfile.tsx
  src/components/timetable/Button/CreateTimetableBtn.tsx
  src/components/timetable/Grid/LectureSticker.tsx
  src/components/timetable/LectureBottomSheet/AddClass/ClassSelectModal.tsx
  src/components/timetable/LectureBottomSheet/AddClass/MajorList.tsx
  src/components/timetable/LectureBottomSheet/AddClass/index.tsx
  src/components/timetable/LectureBottomSheet/index.tsx
  src/components/timetable/StatusBar.tsx
  src/components/timetable/index.tsx
  src/pages/TimetablePage/MyTimetablePage.tsx
  src/util/timetableUtil.ts
Labels: enhancement

#75 [#74] Calendar API 손보기
  src/api/hooks/calendar.ts
  src/api/hooks/home_sub.ts
  src/api/types/calendar.ts
  src/api/types/home_sub.ts
  src/components/calendar/AcademicCalendar.tsx
  src/components/calendar/EventRow.tsx
  src/components/home/Carousel/index.tsx
  src/pages/SchedulePage.tsx
  src/types/calendar.ts
  src/types/home_sub.ts
  src/util/academicCalendar.ts
Labels: enhancement

#72 [배포] 임시 비밀번호 발급 & Reading Key Expiration Info & MyPage UX Improve
  .github/workflows/deploy.yml
  package.json
  src/api/hooks/attendance.ts
  src/api/hooks/auth.ts
  src/api/hooks/calendar.ts
  src/api/hooks/community.ts
  src/api/hooks/home_sub.ts
  src/api/hooks/timetable.ts
  src/api/hooks/user.ts
  src/api/types/calendar.ts
  src/api/types/community.ts
  src/api/types/home_sub.ts
  src/api/types/user.ts
  src/assets/KUONAIR.jpg
  src/components/calendar/AcademicCalendar.tsx
  src/components/calendar/EventRow.tsx
  src/components/community/post/Comment.tsx
  src/components/community/post/CommentHeader.tsx
  src/components/community/post/CommentReply.tsx
  src/components/community/post/Post.tsx
  src/components/community/post/UtilButton.tsx
  src/components/home/Announcement/InsituteProfile.tsx
  src/components/home/Carousel/index.tsx
  src/components/mypage/Contents/ChangePassword.tsx
  src/components/mypage/Contents/Community/CommentCard.tsx
  src/components/mypage/Contents/Community/LikedPost.tsx
  src/components/mypage/Contents/Community/MyComments.tsx
  src/components/mypage/Contents/Community/MyPost.tsx
  src/components/mypage/Contents/Community/MyScrap.tsx
  src/components/mypage/Contents/DeleteAccount.tsx
  src/components/mypage/Contents/ExchangeProfile.tsx
  src/components/mypage/Contents/MyCommunity.tsx
  src/components/mypage/Contents/PointShop/CharacterTicket.tsx
  src/components/mypage/Contents/PointShop/ReviewKeyExpirationCard.tsx
  src/components/mypage/Contents/PointShop/Showcase.tsx
  src/components/timetable/Button/CreateTimetableBtn.tsx
  src/components/timetable/Grid/LectureSticker.tsx
  src/components/timetable/LectureBottomSheet/AddClass/ClassSelectModal.tsx
  src/components/timetable/LectureBottomSheet/AddClass/MajorList.tsx
  src/components/timetable/LectureBottomSheet/AddClass/index.tsx
  src/components/timetable/LectureBottomSheet/index.tsx
  src/components/timetable/StatusBar.tsx
  src/components/timetable/index.tsx
  src/components/ui/modal/AlertModal.tsx
  src/lib/recipes/tag.ts
  src/lib/router/router.tsx
  src/lib/school-institute/broadcasts.ts
  src/pages/LoginPage.tsx
  src/pages/PasswordResetPage.tsx
  src/pages/SchedulePage.tsx
  src/pages/TimetablePage/MyTimetablePage.tsx
  src/types/calendar.ts
  src/types/community.ts
  src/types/home_sub.ts
  src/util/academicCalendar.ts
  src/util/getCommentUsername.ts
  src/util/isAuthorMatchingPostAnonymity.ts
  src/util/timetableUtil.ts
  src/util/useGetPostQueryKey.ts
  yarn.lock
Labels: Deploy

#85 fix: 회원가입 이메일 인증코드 valid check
  src/pages/RegisterPage.tsx
Labels: bug
