Repository DevKor-github/ku-key_front, pull requests merged in 2024-10, with the labels that each got.

#87 feat: menu에 로그인 항목 넣기
  src/components/HeaderMenu.tsx
  src/lib/recipes/input.ts
Labels: enhancement

#81 Feat/log
  package.json
  src/App.tsx
  src/util/AmplitudeProvider.tsx
  yarn.lock
Labels: enhancement

#89 fix: Footer 라우팅 버그, 메뉴 수정
  src/App.tsx
  src/components/Footer.tsx
  src/lib/router/footer-route.ts
  src/pages/ClubPage.tsx
  src/pages/CommunityPage/PostViewPage.tsx
  src/pages/CourseReviewPage/ReviewDetailPage.tsx
  src/pages/CourseReviewPage/WriteReviewPage.tsx
  src/util/ScrollToTop.tsx
  src/util/useScrollUp.ts
Labels: bug

#88 [배포] 메타태그, 사이드바, 앰플리튜드, 이메일 valid check ...
  index.html
  package.json
  panda.config.ts
  src/App.tsx
  src/assets/CharacterDefault.png
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/HeaderMenu.tsx
  src/components/MainLayout.tsx
  src/components/MetaTag.tsx
  src/components/header/NavLinkButton.tsx
  src/components/header/SideTabLogInLink.tsx
  src/components/header/SideTabProfile.tsx
  src/components/ui/profile/CharacterConfig.ts
  src/components/ui/sheet/index.tsx
  src/lib/recipes/index.ts
  src/lib/recipes/input.ts
  src/lib/recipes/sheet.ts
  src/lib/router/footer-route.ts
  src/pages/ClubPage.tsx
  src/pages/CommunityPage/PostViewPage.tsx
  src/pages/CourseReviewPage/ReviewDetailPage.tsx
  src/pages/CourseReviewPage/WriteReviewPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/SchedulePage.tsx
  src/util/AmplitudeProvider.tsx
  src/util/ScrollToTop.tsx
  src/util/useScrollUp.ts
  yarn.lock
Labels: Deploy

#91 fix KK-1 회원가입 필드명 변경
  src/components/register/UserInfoForm.tsx
Labels: emergency

#94 [KK-52] feat: 미인증 유저 알람 기능 막기
  src/components/header/NotifyWindow.tsx
Labels: enhancement

#96 feat: PR Template
  .github/pull-request-template.md
Labels: enhancement

#101 [KK-56] fix: 다른 path에서 마이페이지 들어갔을 시 뒤로가기가 되지 않는 버그
  src/components/Header.tsx
  src/components/mypage/MyPageContents.tsx
  src/pages/LandingPage.tsx
Labels: bug

#103 [KK-86] fix(typo): 잘못 표기된 포인트 instruction
  src/components/ui/modal/SugarModal.tsx
Labels: bug

#102 fix(mod): Amplitude Key 없으면 안 달리도록, Console Warning 해결
  src/util/AmplitudeProvider.tsx
Labels: bug

#100 [KK-24] fix(rwd): Schedule Page lgDown 사이징 대응
  src/components/calendar/AcademicCalendar.tsx
  src/components/calendar/EventRow.tsx
  src/pages/SchedulePage.tsx
Labels: bug

#95 [KK-59] fix: 강의평 좋아요 모아보기 임시 배제
  src/pages/CourseReviewPage/ReviewPage.tsx
Labels: bug

#110 [KK-49] feat: username 변경 시 validation check
  src/components/mypage/Contents/PublicProfile.tsx
Labels: bug

#117 [KK-106] fix: no-cache 로 img url로 blob fetch
  src/util/create-file-from-url.ts
Labels: emergency
